enabled: true
source:
  type: api
  path: ""
allocation:
  multi_month: linear
value_types:
  - total_affected
  - affected
  - injured
  - homeless
hazard_map: {}
country_aliases: {}
classif_keys:
  - "nat-cli-dro-dro"
  - "nat-met-sto-tro"
  - "nat-hyd-flo-riv"
  - "nat-hyd-flo-fla"
include_hist: false
default_from_year: 2024
default_to_year: 2025
iso: []
