# Pythia
# Copyright (c) 2025 Kevin Wyjad
# Licensed under the Pythia Non-Commercial Public License v1.0.
# See the LICENSE file in the project root for details.

enabled: true
source:
  type: api
  path: ""
allocation:
  multi_month: sticky  # full PA counted in each overlapping month
value_types:
  - total_affected
  - affected
  - injured
  - homeless
hazard_map: {}
country_aliases: {}
classif_keys:
  - "nat-cli-dro-dro"
  - "nat-met-sto-tro"
  - "nat-hyd-flo-riv"
  - "nat-hyd-flo-fla"
include_hist: false
default_from_year: 2022
default_to_year: null
iso: []
