# Pythia
# Copyright (c) 2025 Kevin Wyjad
# Licensed under the Pythia Non-Commercial Public License v1.0.
# See the LICENSE file in the project root for details.

enabled: true
window_days: 365
retry:
  tries: 5
  backoff: 2
endpoints:
  event_list: "https://www.gdacs.org/gdacsapi/api/events/geteventlist"
  event_details: "https://www.gdacs.org/gdacsapi/api/events/getevent"
hazard_map:
  FL: flood
  TC: tropical_cyclone
  VO: volcano
  WF: wildfire
  DR: drought
severity_map:
  Green: 0
  Orange: 1
  Red: 2
country_aliases: {}
