# Pythia
# Copyright (c) 2025 Kevin Wyjad
# Licensed under the Pythia Non-Commercial Public License v1.0.
# See the LICENSE file in the project root for details.

enabled: true
sources:
  - name: mvam_ifc_global
    kind: json
    url: https://databridges.vam.wfp.org/api/external/FoodSecurity/List
    params:
      indicatorCode: insufficient_food_consumption
      dateFrom: "{{ start_iso }}"
      dateTo: "{{ end_iso }}"
      pageSize: 5000
    pagination:
      type: page
      param: pageNumber
      start: 1
      page_size_param: pageSize
      page_size: 5000
      max_pages: 20
auth: {}
