# Pythia
# Copyright (c) 2025 Kevin Wyjad
# Licensed under the Pythia Non-Commercial Public License v1.0.
# See the LICENSE file in the project root for details.

enabled: true
sources:
  - name: cholera_global
    kind: json
    url: https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Cholera_Weekly/FeatureServer/0/query
    params:
      where: "1=1"
      outFields: "*"
      f: json
      resultRecordCount: 2000
      resultOffset: 0
      orderByFields: "ReportDate"
    pagination:
      type: offset
      offset_param: resultOffset
      page_size_param: resultRecordCount
      page_size: 2000
      max_pages: 50
    time_keys: ["ReportDate", "EpiWeek", "EpiYear"]
    country_keys: ["Country", "ISO3", "WHO_region"]
    case_keys: ["Cases", "New_Cases"]
    disease: cholera
auth: {}
