# Pythia
# Copyright (c) 2025 Kevin Wyjad
# Licensed under the Pythia Non-Commercial Public License v1.0.
# See the LICENSE file in the project root for details.

[env]
USE_PARQUET = "false"
PYTHIA_LOCAL_CSV_PATH = "forecasts.csv"

pythia_api_token = "CHANGE_THIS_TOKEN"
